# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_e0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_e1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper_l_finger_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper_r_finger_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_s0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_s1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_w0:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  left_w1:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  left_w2:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  right_e0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  right_e1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper_l_finger_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper_r_finger_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_s0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  right_s1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  right_w0:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  right_w1:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  right_w2:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0